icons:[














































 





{ic:"fab fa-black-tie"}, 
{ic:"fab fa-blackberry"}, 
{ic:"fab fa-blogger"}, 
{ic:"fab fa-blogger-b"}, 
{ic:"fab fa-bluetooth"}, 
{ic:"fab fa-bluetooth-b"}, 
{ic:"fab fa-bootstrap"}, 
{ic:"fab fa-btc"}, 
{ic:"fab fa-buffer"}, 
{ic:"fab fa-buromobelexperte"}, 
{ic:"fab fa-buy-n-large"}, 
{ic:"fab fa-buysellads"}, 
{ic:"fab fa-canadian-maple-leaf"}, 
{ic:"fab fa-cc-amazon-pay"}, 
{ic:"fab fa-cc-amex"}, 
{ic:"fab fa-cc-apple-pay"}, 
{ic:"fab fa-cc-diners-club"}, 
{ic:"fab fa-cc-discover"}, 
{ic:"fab fa-cc-jcb"}, 
{ic:"fab fa-cc-mastercard"}, 
{ic:"fab fa-cc-paypal"}, 
{ic:"fab fa-cc-stripe"}, 
{ic:"fab fa-cc-visa"}, 
{ic:"fab fa-centercode"}, 
{ic:"fab fa-centos"}, 
{ic:"fab fa-chrome"}, 
{ic:"fab fa-chromecast"}, 
{ic:"fab fa-cloudflare"}, 
{ic:"fab fa-cloudscale"}, 
{ic:"fab fa-cloudsmith"}, 
{ic:"fab fa-cloudversify"}, 
{ic:"fab fa-codepen"}, 
{ic:"fab fa-codiepie"}, 
{ic:"fab fa-confluence"}, 
{ic:"fab fa-connectdevelop"}, 
{ic:"fab fa-contao"}, 
{ic:"fab fa-cotton-bureau"}, 
{ic:"fab fa-cpanel"}, 
{ic:"fab fa-creative-commons"}, 
{ic:"fab fa-creative-commons-by"}, 
{ic:"fab fa-creative-commons-nc"}, 
{ic:"fab fa-creative-commons-nc-eu"}, 
{ic:"fab fa-creative-commons-nc-jp"}, 
{ic:"fab fa-creative-commons-nd"}, 
{ic:"fab fa-creative-commons-pd"}, 
{ic:"fab fa-creative-commons-pd-alt"}, 
{ic:"fab fa-creative-commons-remix"}, 
{ic:"fab fa-creative-commons-sa"}, 
{ic:"fab fa-creative-commons-sampling"}, 
{ic:"fab fa-creative-commons-sampling-plus"}, 
{ic:"fab fa-creative-commons-share"}, 
{ic:"fab fa-creative-commons-zero"}, 
{ic:"fab fa-critical-role"}, 
{ic:"fab fa-css3"}, 
{ic:"fab fa-css3-alt"}, 
{ic:"fab fa-cuttlefish"}, 
{ic:"fab fa-d-and-d"}, 
{ic:"fab fa-d-and-d-beyond"}, 
{ic:"fab fa-dailymotion"}, 
{ic:"fab fa-dashcube"}, 
{ic:"fab fa-deezer"}, 
{ic:"fab fa-delicious"}, 
{ic:"fab fa-deploydog"}, 
{ic:"fab fa-deskpro"}, 
{ic:"fab fa-dev"}, 
{ic:"fab fa-deviantart"}, 
{ic:"fab fa-dhl"}, 
{ic:"fab fa-diaspora"}, 
{ic:"fab fa-digg"}, 
{ic:"fab fa-digital-ocean"}, 
{ic:"fab fa-discord"}, 
{ic:"fab fa-discourse"}, 
{ic:"fab fa-dochub"}, 
{ic:"fab fa-docker"}, 
{ic:"fab fa-draft2digital"}, 
{ic:"fab fa-dribbble"}, 
{ic:"fab fa-dribbble-square"}, 
{ic:"fab fa-dropbox"}, 
{ic:"fab fa-drupal"}, 
{ic:"fab fa-dyalog"}, 
{ic:"fab fa-earlybirds"}, 
{ic:"fab fa-ebay"}, 
{ic:"fab fa-edge"}, 
{ic:"fab fa-edge-legacy"}, 
{ic:"fab fa-elementor"}, 
{ic:"fab fa-ello"}, 
{ic:"fab fa-ember"}, 
{ic:"fab fa-empire"}, 
{ic:"fab fa-envira"}, 
{ic:"fab fa-erlang"}, 
{ic:"fab fa-ethereum"}, 
{ic:"fab fa-etsy"}, 
{ic:"fab fa-evernote"}, 
{ic:"fab fa-expeditedssl"}, 
{ic:"fab fa-facebook"}, 
{ic:"fab fa-facebook-f"}, 
{ic:"fab fa-facebook-messenger"}, 
{ic:"fab fa-facebook-square"}, 
{ic:"fab fa-fantasy-flight-games"}, 
{ic:"fab fa-fedex"}, 
{ic:"fab fa-fedora"}, 
{ic:"fab fa-figma"}, 
{ic:"fab fa-firefox"}, 
{ic:"fab fa-firefox-browser"}, 
{ic:"fab fa-first-order"}, 
{ic:"fab fa-first-order-alt"}, 
{ic:"fab fa-firstdraft"}, 
{ic:"fab fa-flickr"}, 
{ic:"fab fa-flipboard"}, 
{ic:"fab fa-fly"}, 
{ic:"fab fa-font-awesome"}, 
{ic:"fab fa-font-awesome-alt"}, 
{ic:"fab fa-font-awesome-flag"}, 
{ic:"fab fa-fonticons"}, 
{ic:"fab fa-fonticons-fi"}, 
{ic:"fab fa-fort-awesome"}, 
{ic:"fab fa-fort-awesome-alt"}, 
{ic:"fab fa-forumbee"}, 
{ic:"fab fa-foursquare"}, 
{ic:"fab fa-free-code-camp"}, 
{ic:"fab fa-freebsd"}, 
{ic:"fab fa-fulcrum"}, 
{ic:"fab fa-galactic-republic"}, 
{ic:"fab fa-galactic-senate"}, 
{ic:"fab fa-get-pocket"}, 
{ic:"fab fa-gg"}, 
{ic:"fab fa-gg-circle"}, 
{ic:"fab fa-git"}, 
{ic:"fab fa-git-alt"}, 
{ic:"fab fa-git-square"}, 
{ic:"fab fa-github"}, 
{ic:"fab fa-github-alt"}, 
{ic:"fab fa-github-square"}, 
{ic:"fab fa-gitkraken"}, 
{ic:"fab fa-gitlab"}, 
{ic:"fab fa-gitter"}, 
{ic:"fab fa-glide"}, 
{ic:"fab fa-glide-g"}, 
{ic:"fab fa-gofore"}, 
{ic:"fab fa-goodreads"}, 
{ic:"fab fa-goodreads-g"}, 
{ic:"fab fa-google"}, 
{ic:"fab fa-google-drive"}, 
{ic:"fab fa-google-pay"}, 
{ic:"fab fa-google-play"}, 
{ic:"fab fa-google-plus"}, 
{ic:"fab fa-google-plus-g"}, 
{ic:"fab fa-google-plus-square"}, 
{ic:"fab fa-google-wallet"}, 
{ic:"fab fa-gratipay"}, 
{ic:"fab fa-grav"}, 
{ic:"fab fa-gripfire"}, 
{ic:"fab fa-grunt"}, 
{ic:"fab fa-guilded"}, 
{ic:"fab fa-gulp"}, 
{ic:"fab fa-hacker-news"}, 
{ic:"fab fa-hacker-news-square"}, 
{ic:"fab fa-hackerrank"}, 
{ic:"fab fa-hips"}, 
{ic:"fab fa-hire-a-helper"}, 
{ic:"fab fa-hive"}, 
{ic:"fab fa-hooli"}, 
{ic:"fab fa-hornbill"}, 
{ic:"fab fa-hotjar"}, 
{ic:"fab fa-houzz"}, 
{ic:"fab fa-html5"}, 
{ic:"fab fa-hubspot"}, 
{ic:"fab fa-ideal"}, 
{ic:"fab fa-imdb"}, 
{ic:"fab fa-innosoft"}, 
{ic:"fab fa-instagram"}, 
{ic:"fab fa-instagram-square"}, 
{ic:"fab fa-instalod"}, 
{ic:"fab fa-intercom"}, 
{ic:"fab fa-internet-explorer"}, 
{ic:"fab fa-invision"}, 
{ic:"fab fa-ioxhost"}, 
{ic:"fab fa-itch-io"}, 
{ic:"fab fa-itunes"}, 
{ic:"fab fa-itunes-note"}, 
{ic:"fab fa-java"}, 
{ic:"fab fa-jedi-order"}, 
{ic:"fab fa-jenkins"}, 
{ic:"fab fa-jira"}, 
{ic:"fab fa-joget"}, 
{ic:"fab fa-joomla"}, 
{ic:"fab fa-js"}, 
{ic:"fab fa-js-square"}, 
{ic:"fab fa-jsfiddle"}, 
{ic:"fab fa-kaggle"}, 
{ic:"fab fa-keybase"}, 
{ic:"fab fa-keycdn"}, 
{ic:"fab fa-kickstarter"}, 
{ic:"fab fa-kickstarter-k"}, 
{ic:"fab fa-korvue"}, 
{ic:"fab fa-laravel"}, 
{ic:"fab fa-lastfm"}, 
{ic:"fab fa-lastfm-square"}, 
{ic:"fab fa-leanpub"}, 
{ic:"fab fa-less"}, 
{ic:"fab fa-line"}, 
{ic:"fab fa-linkedin"}, 
{ic:"fab fa-linkedin-in"}, 
{ic:"fab fa-linode"}, 
{ic:"fab fa-linux"}, 
{ic:"fab fa-lyft"}, 
{ic:"fab fa-magento"}, 
{ic:"fab fa-mailchimp"}, 
{ic:"fab fa-mandalorian"}, 
{ic:"fab fa-markdown"}, 
{ic:"fab fa-mastodon"}, 
{ic:"fab fa-maxcdn"}, 
{ic:"fab fa-mdb"}, 
{ic:"fab fa-medapps"}, 
{ic:"fab fa-medium"}, 
{ic:"fab fa-medium-m"}, 
{ic:"fab fa-medrt"}, 
{ic:"fab fa-meetup"}, 
{ic:"fab fa-megaport"}, 
{ic:"fab fa-mendeley"}, 
{ic:"fab fa-microblog"}, 
{ic:"fab fa-microsoft"}, 
{ic:"fab fa-mix"}, 
{ic:"fab fa-mixcloud"}, 
{ic:"fab fa-mixer"}, 
{ic:"fab fa-mizuni"}, 
{ic:"fab fa-modx"}, 
{ic:"fab fa-monero"}, 
{ic:"fab fa-napster"}, 
{ic:"fab fa-neos"}, 
{ic:"fab fa-nimblr"}, 
{ic:"fab fa-node"}, 
{ic:"fab fa-node-js"}, 
{ic:"fab fa-npm"}, 
{ic:"fab fa-ns8"}, 
{ic:"fab fa-nutritionix"}, 
{ic:"fab fa-octopus-deploy"}, 
{ic:"fab fa-odnoklassniki"}, 
{ic:"fab fa-odnoklassniki-square"}, 
{ic:"fab fa-old-republic"}, 
{ic:"fab fa-opencart"}, 
{ic:"fab fa-openid"}, 
{ic:"fab fa-opera"}, 
{ic:"fab fa-optin-monster"}, 
{ic:"fab fa-orcid"}, 
{ic:"fab fa-osi"}, 
{ic:"fab fa-page4"}, 
{ic:"fab fa-pagelines"}, 
{ic:"fab fa-palfed"}, 
{ic:"fab fa-patreon"}, 
{ic:"fab fa-paypal"}, 
{ic:"fab fa-penny-arcade"}, 
{ic:"fab fa-perbyte"}, 
{ic:"fab fa-periscope"}, 
{ic:"fab fa-phabricator"}, 
{ic:"fab fa-phoenix-framework"}, 
{ic:"fab fa-phoenix-squadron"}, 
{ic:"fab fa-php"}, 
{ic:"fab fa-pied-piper"}, 
{ic:"fab fa-pied-piper-alt"}, 
{ic:"fab fa-pied-piper-hat"}, 
{ic:"fab fa-pied-piper-pp"}, 
{ic:"fab fa-pied-piper-square"}, 
{ic:"fab fa-pinterest"}, 
{ic:"fab fa-pinterest-p"}, 
{ic:"fab fa-pinterest-square"}, 
{ic:"fab fa-playstation"}, 
{ic:"fab fa-product-hunt"}, 
{ic:"fab fa-pushed"}, 
{ic:"fab fa-python"}, 
{ic:"fab fa-qq"}, 
{ic:"fab fa-quinscape"}, 
{ic:"fab fa-quora"}, 
{ic:"fab fa-r-project"}, 
{ic:"fab fa-raspberry-pi"}, 
{ic:"fab fa-ravelry"}, 
{ic:"fab fa-react"}, 
{ic:"fab fa-reacteurope"}, 
{ic:"fab fa-readme"}, 
{ic:"fab fa-rebel"}, 
{ic:"fab fa-red-river"}, 
{ic:"fab fa-reddit"}, 
{ic:"fab fa-reddit-alien"}, 
{ic:"fab fa-reddit-square"}, 
{ic:"fab fa-redhat"}, 
{ic:"fab fa-renren"}, 
{ic:"fab fa-replyd"}, 
{ic:"fab fa-researchgate"}, 
{ic:"fab fa-resolving"}, 
{ic:"fab fa-rev"}, 
{ic:"fab fa-rocketchat"}, 
{ic:"fab fa-rockrms"}, 
{ic:"fab fa-rust"}, 
{ic:"fab fa-safari"}, 
{ic:"fab fa-salesforce"}, 
{ic:"fab fa-sass"}, 
{ic:"fab fa-schlix"}, 
{ic:"fab fa-scribd"}, 
{ic:"fab fa-searchengin"}, 
{ic:"fab fa-sellcast"}, 
{ic:"fab fa-sellsy"}, 
{ic:"fab fa-servicestack"}, 
{ic:"fab fa-shirtsinbulk"}, 
{ic:"fab fa-shopify"}, 
{ic:"fab fa-shopware"}, 
{ic:"fab fa-simplybuilt"}, 
{ic:"fab fa-sistrix"}, 
{ic:"fab fa-sith"}, 
{ic:"fab fa-sketch"}, 
{ic:"fab fa-skyatlas"}, 
{ic:"fab fa-skype"}, 
{ic:"fab fa-slack"}, 
{ic:"fab fa-slack-hash"}, 
{ic:"fab fa-slideshare"}, 
{ic:"fab fa-snapchat"}, 
{ic:"fab fa-snapchat-ghost"}, 
{ic:"fab fa-snapchat-square"}, 
{ic:"fab fa-soundcloud"}, 
{ic:"fab fa-sourcetree"}, 
{ic:"fab fa-speakap"}, 
{ic:"fab fa-speaker-deck"}, 
{ic:"fab fa-spotify"}, 
{ic:"fab fa-squarespace"}, 
{ic:"fab fa-stack-exchange"}, 
{ic:"fab fa-stack-overflow"}, 
{ic:"fab fa-stackpath"}, 
{ic:"fab fa-staylinked"}, 
{ic:"fab fa-steam"}, 
{ic:"fab fa-steam-square"}, 
{ic:"fab fa-steam-symbol"}, 
{ic:"fab fa-sticker-mule"}, 
{ic:"fab fa-strava"}, 
{ic:"fab fa-stripe"}, 
{ic:"fab fa-stripe-s"}, 
{ic:"fab fa-studiovinari"}, 
{ic:"fab fa-stumbleupon"}, 
{ic:"fab fa-stumbleupon-circle"}, 
{ic:"fab fa-superpowers"}, 
{ic:"fab fa-supple"}, 
{ic:"fab fa-suse"}, 
{ic:"fab fa-swift"}, 
{ic:"fab fa-symfony"}, 
{ic:"fab fa-teamspeak"}, 
{ic:"fab fa-telegram"}, 
{ic:"fab fa-telegram-plane"}, 
{ic:"fab fa-tencent-weibo"}, 
{ic:"fab fa-the-red-yeti"}, 
{ic:"fab fa-themeco"}, 
{ic:"fab fa-themeisle"}, 
{ic:"fab fa-think-peaks"}, 
{ic:"fab fa-tiktok"}, 
{ic:"fab fa-trade-federation"}, 
{ic:"fab fa-trello"}, 
{ic:"fab fa-tumblr"}, 
{ic:"fab fa-tumblr-square"}, 
{ic:"fab fa-twitch"}, 
{ic:"fab fa-twitter"}, 
{ic:"fab fa-twitter-square"}, 
{ic:"fab fa-typo3"}, 
{ic:"fab fa-uber"}, 
{ic:"fab fa-ubuntu"}, 
{ic:"fab fa-uikit"}, 
{ic:"fab fa-umbraco"}, 
{ic:"fab fa-uncharted"}, 
{ic:"fab fa-uniregistry"}, 
{ic:"fab fa-unity"}, 
{ic:"fab fa-unsplash"}, 
{ic:"fab fa-untappd"}, 
{ic:"fab fa-ups"}, 
{ic:"fab fa-usb"}, 
{ic:"fab fa-usps"}, 
{ic:"fab fa-ussunnah"}, 
{ic:"fab fa-vaadin"}, 
{ic:"fab fa-viacoin"}, 
{ic:"fab fa-viadeo"}, 
{ic:"fab fa-viadeo-square"}, 
{ic:"fab fa-viber"}, 
{ic:"fab fa-vimeo"}, 
{ic:"fab fa-vimeo-square"}, 
{ic:"fab fa-vimeo-v"}, 
{ic:"fab fa-vine"}, 
{ic:"fab fa-vk"}, 
{ic:"fab fa-vnv"}, 
{ic:"fab fa-vuejs"}, 
{ic:"fab fa-watchman-monitoring"}, 
{ic:"fab fa-waze"}, 
{ic:"fab fa-weebly"}, 
{ic:"fab fa-weibo"}, 
{ic:"fab fa-weixin"}, 
{ic:"fab fa-whatsapp"}, 
{ic:"fab fa-whatsapp-square"}, 
{ic:"fab fa-whmcs"}, 
{ic:"fab fa-wikipedia-w"}, 
{ic:"fab fa-windows"}, 
{ic:"fab fa-wix"}, 
{ic:"fab fa-wizards-of-the-coast"}, 
{ic:"fab fa-wodu"}, 
{ic:"fab fa-wolf-pack-battalion"}, 
{ic:"fab fa-wordpress"}, 
{ic:"fab fa-wordpress-simple"}, 
{ic:"fab fa-wpbeginner"}, 
{ic:"fab fa-wpexplorer"}, 
{ic:"fab fa-wpforms"}, 
{ic:"fab fa-wpressr"}, 
{ic:"fab fa-xbox"}, 
{ic:"fab fa-xing"}, 
{ic:"fab fa-xing-square"}, 
{ic:"fab fa-y-combinator"}, 
{ic:"fab fa-yahoo"}, 
{ic:"fab fa-yammer"}, 
{ic:"fab fa-yandex"}, 
{ic:"fab fa-yandex-international"}, 
{ic:"fab fa-yarn"}, 
{ic:"fab fa-yelp"}, 
{ic:"fab fa-yoast"}, 
{ic:"fab fa-youtube"}, 
{ic:"fab fa-youtube-square"}, 
{ic:"fab fa-zhihu"},] 